### ISSUE TITLE
Repo no longer available

### ISSUE THREAD

**Issue by isi-wault** [codeproject/CodeProject.AI-Text2Image#1]
Good Morning,

The repo (https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/) that this calls when it tries to process a request no longer exists on huggingface. So on initial setup it fails. Also, it seems like any changes to the config (like changing this repo) don't take effect until the entire CodeProject.AI server is restarted, instead of on restart of the Text2Image module.

Still haven't got this to work even with a different repo but that's probably on me being new to this stuff.

Thanks for the work!

**Comment by ChrisMaunder** [comment]
Seems to be back.

> changes to the config (like changing this repo) don't take effect until the entire CodeProject.AI server is restarted

Correct
